### ISSUE TITLE
ReferenceError: error is not defined

### ISSUE THREAD

**Issue by phra** [mikeal/r2#19]
after failing trying to run r2 on runkit, i fallback on working on my local machine but i still got an error:

```
╭─phra at kali in /tmp
╰─λ node -v                                                                                                                                                      0 < 11:54:08
v8.4.0

╭─phra at kali in /tmp
╰─λ cat index.js                                                                                                                                                 0 < 11:54:02
const r2 = require('r2')
const to = require('await-to-ts')
const assert = require('assert')

const URLS = [1,2,3,4,5,6,7,8,9,10].map(i => `https://jsonplaceholder.typicode.com/posts/${i}`)

(async () => {
  const promises = URLS.map(url => r2(url))
  const [err, res] = await to(promises)
  assert.ifError(err)
  res.forEach(console.log.bind(console))
})()⏎                                                                                                                                                                        

╭─phra at kali in /tmp
╰─λ node index.js                                                                                                                                                0 < 11:54:05
/tmp/node_modules/r2/clayconfig.js:5
if(!config.raw.name)	            error( "package.json should have a name value")
                    	            ^

ReferenceError: error is not defined
    at Object.<anonymous> (/tmp/node_modules/r2/clayconfig.js:5:34)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/node_modules/r2/index.js:15:14)
    at Module._compile (module.js:573:30)
```

**Comment by phra** [comment]
this execution path is triggered when you are using `r2` in a project with a `package.json` without `name` and `version` property.
after adding those properties i got again:
```
╭─phra at kali in /tmp
╰─λ node index.js                                                                                                                                                0 < 12:01:14
Welcome to 3VOT
/tmp/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/tmp/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/tmp/node_modules/r2/index.js:19:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/index.js:1:74)
```

**Comment by thechriswalker** [comment]
As on runkit, and my comment on the previous issue:

> That's not the `r2` you are looking for... https://www.npmjs.com/package/r2 is something totally different (https://github.com/3vot/clay by the look of it - must have been published as r2 at some point...)

**Comment by phra** [comment]
closing due to wrong import. `r2` on npm is not this `r2`.
