### ISSUE TITLE
The automated release is failing 🚨

### ISSUE THREAD

**Issue by mikeal** [mikeal/r2#74]
## :rotating_light: The automated release from the `master` branch failed. :rotating_light:

I recommend you give this issue a high priority, so other packages depending on you could benefit from your bug fixes and new features.

You can find below the list of errors reported by **semantic-release**. Each one of them has to be resolved in order to automatically publish your package. I’m sure you can resolve this 💪.

Errors are usually caused by a misconfiguration or an authentication problem. With each error reported below you will find explanation and guidance to help you to resolve it.

Once all the errors are resolved, **semantic-release** will release your package the next time you push a commit to the `master` branch. You can also manually restart the failed CI job that runs **semantic-release**.

If you are not sure how to resolve this, here is some links that can help you:
- [Usage documentation](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/README.md)
- [Frequently Asked Questions](https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md)
- [Support channels](https://github.com/semantic-release/semantic-release#get-help)

If those don’t help, or if this issue is reporting something you think isn’t right, you can always ask the humans behind **[semantic-release](https://github.com/semantic-release/semantic-release/issues/new)**.

---

### Invalid npm token.

The [npm token](https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) configured in the `NPM_TOKEN` environment variable must be a valid [token](https://docs.npmjs.com/getting-started/working_with_tokens) allowing to publish to the registry `https://registry.npmjs.org/`.

If you are using Two-Factor Authentication, make configure the `auth-only` [level](https://docs.npmjs.com/getting-started/using-two-factor-authentication#levels-of-authentication) is supported. **semantic-release** cannot publish with the default `auth-and-writes` level.

Please make sure to set the `NPM_TOKEN` environment variable in your CI with the exact value of the npm token.

---

Good luck with your project ✨

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by gr2m** [comment]
@mikeal can you re-run `semantic-release-cli setup`? That’ll fix the tokens. npm invalided all tokens recently

**Comment by mikeal** [comment]
@gr2m I got this error:

```
(master)⚡ % semantic-release-cli setup                                                                                                                             ~/git/r2
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? mikeal
ERR! semantic-release Error: Could not login to npm.
ERR! semantic-release     at getNpmToken (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:55:21)
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:68:7)
ERR! semantic-release  { Error: Could not login to npm.
ERR! semantic-release     at getNpmToken (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:55:21)
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:68:7)
ERR! semantic-release   stack:
ERR! semantic-release    'Error: Could not login to npm.\n    at getNpmToken (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:55:21)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
(master)⚡ [1] % semantic-release-cli setup
```

**Comment by gr2m** [comment]
would you mind if I created a dedicated npm account only for `r2` releases? It’s what I usually do for my bigger repositories, it’s also more secure because npm tokens cannot be scoped by package and if someone were to get access to your token they could do some damage to all npm packages you have write access to

**Comment by mikeal** [comment]
Go for it :)

**Comment by gr2m** [comment]
can you invite https://www.npmjs.com/~r2bot as collaborator to the `r2` package?
